import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import App from "../App";
import { ApiError, generateInfrastructure } from "../services/apiClient";
import type { GenerateResponse } from "../types/api";

vi.mock("../services/apiClient", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../services/apiClient")>();
  return {
    ...actual,
    analyzeManifest: vi.fn(),
    generateInfrastructure: vi.fn(),
  };
});

const mockedGenerate = vi.mocked(generateInfrastructure);

const CONFIG = {
  source_type: "kubernetes",
  application: "rest-api-app",
  namespace: "default",
  replicas: 2,
  cpu_request: 2,
  cpu_limit: 2,
  memory_request_gb: 4,
  memory_limit_gb: 4,
  autoscaling_enabled: false,
  container_image: null,
  cloud_provider: null,
  region: null,
  instance_type: null,
  instance_count: null,
  storage_gb: 50,
  parser_warnings: null,
};

function makeResult(): GenerateResponse {
  return {
    generation_id: "gen-123",
    status: "recommended",
    selected_configuration: CONFIG,
    target_selection: {
      target: "kubernetes",
      source: "auto",
      explanation: "Rule 3: autoscaling with bursty traffic uses the Kubernetes HPA.",
    },
    requirements: {
      cpu_cores: 2,
      memory_gb: 4,
      replica_estimate: 2,
      replica_minimum: 2,
      storage_gb: 50,
      autoscaling_required: false,
      peak_factor: 3,
      notes: ["peak_factor 3 from RPS ratio"],
    },
    artifacts: [
      {
        target: "kubernetes",
        filename: "deployment.yaml",
        content: "# Generated by EcoOps AI\napiVersion: apps/v1\nkind: Deployment\n",
        round_trip_valid: true,
        notes: ["Note text"],
      },
    ],
    evaluation: {
      status: "recommended",
      requirements: {
        cpu_cores: 2,
        memory_gb: 4,
        replica_estimate: 2,
        replica_minimum: 2,
        storage_gb: 50,
        autoscaling_required: false,
        peak_factor: 3,
        notes: [],
      },
      candidates: [
        {
          plan: {
            variant: "balanced",
            summary: "The requirement estimate as-is",
            configuration: { ...CONFIG, storage_gb: null },
          },
          prediction: {
            cpu_utilization: 0.4,
            memory_utilization: 0.45,
            model_type: "mock",
            model_created_at: null,
          },
          estimation: {
            estimated_cost_usd: 87.6,
            estimated_energy_kwh: 9.2,
            estimated_carbon_kg_co2e: 4.1,
            active_cpu_vcpus: 1.6,
            active_memory_gb: 3.6,
            assumptions: {
              period_hours: 730,
              cpu_cost_per_vcpu_hour_usd: 0.025,
              memory_cost_per_gb_hour_usd: 0.01,
              cpu_power_watts_per_active_vcpu: 3,
              memory_power_watts_per_active_gb: 0.4,
              data_center_pue: 1.5,
              carbon_intensity_gco2_per_kwh: 475,
            },
            disclaimer: "Heuristic estimates.",
          },
          constraints: { satisfied: true, checks: [], disclaimer: "d" },
          score: {
            score: 0.42,
            grade: "D",
            components: [],
            methodology: "weighted mean",
            disclaimer: "d",
          },
          eligible: true,
          rejection_reasons: [],
        },
        {
          plan: {
            variant: "lean",
            summary: "Smallest sizing",
            configuration: { ...CONFIG, replicas: 1, cpu_request: 1, memory_request_gb: 2, storage_gb: null },
          },
          prediction: {
            cpu_utilization: 0.9,
            memory_utilization: 0.8,
            model_type: "mock",
            model_created_at: null,
          },
          estimation: {
            estimated_cost_usd: 20,
            estimated_energy_kwh: 2,
            estimated_carbon_kg_co2e: 1,
            active_cpu_vcpus: 0.9,
            active_memory_gb: 1.6,
            assumptions: {
              period_hours: 730,
              cpu_cost_per_vcpu_hour_usd: 0.025,
              memory_cost_per_gb_hour_usd: 0.01,
              cpu_power_watts_per_active_vcpu: 3,
              memory_power_watts_per_active_gb: 0.4,
              data_center_pue: 1.5,
              carbon_intensity_gco2_per_kwh: 475,
            },
            disclaimer: "Heuristic estimates.",
          },
          constraints: { satisfied: false, checks: [], disclaimer: "d" },
          score: {
            score: 0.5,
            grade: "C",
            components: [],
            methodology: "weighted mean",
            disclaimer: "d",
          },
          eligible: false,
          rejection_reasons: ["cpu_headroom: predicted 90% > 70%"],
        },
      ],
      selected_index: 0,
      weights_used: {
        resource_efficiency: 0.3,
        energy_efficiency: 0.25,
        carbon_impact: 0.25,
        cost_efficiency: 0.15,
        constraint_compliance: 0.05,
      },
      ranking_explanation: "Selected the 'balanced' candidate with score 0.4200 (D).",
      infeasibility_explanation: null,
      disclaimer: "Prototype heuristics; nothing is deployed.",
    },
  };
}

function openGeneratePage() {
  render(<App />);
  fireEvent.click(screen.getByTestId("entry-generate"));
}

describe("Mode B frontend", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("landing shows the two entry points", () => {
    render(<App />);
    expect(screen.getByTestId("landing")).toBeDefined();
    fireEvent.click(screen.getByTestId("entry-generate"));
    expect(screen.getByTestId("generate-page")).toBeDefined();
  });

  it("analyze entry opens the upload flow", () => {
    render(<App />);
    fireEvent.click(screen.getByTestId("entry-analyze"));
    expect(screen.getByText(/Drag & drop/i)).toBeDefined();
  });

  it("submits the workload form and renders the result screen", async () => {
    mockedGenerate.mockResolvedValueOnce(makeResult());
    openGeneratePage();
    fireEvent.click(screen.getByTestId("generate-submit"));

    await waitFor(() => {
      expect(screen.getByTestId("generation-result")).toBeDefined();
    });
    expect(mockedGenerate).toHaveBeenCalledTimes(1);
    const [workloadArg, targetArg] = mockedGenerate.mock.calls[0];
    expect(workloadArg.application_type).toBe("rest-api");
    expect(targetArg).toBeNull(); // "auto"

    expect(screen.getByTestId("architecture-summary").textContent).toContain("rest-api-app");
    expect(screen.getByTestId("architecture-summary").textContent).toContain("2 cores");
    expect(screen.getByText(/Why this configuration\?/)).toBeDefined();
    expect(screen.getByTestId("rejected-candidates").textContent).toContain("lean");
  });

  it("passes the explicit target through", async () => {
    mockedGenerate.mockResolvedValueOnce(makeResult());
    openGeneratePage();
    fireEvent.change(screen.getByLabelText("Generate configuration for"), {
      target: { value: "kubernetes" },
    });
    fireEvent.click(screen.getByTestId("generate-submit"));
    await waitFor(() => expect(screen.getByTestId("generation-result")).toBeDefined());
    expect(mockedGenerate.mock.calls[0][1]).toBe("kubernetes");
  });

  it("previews and downloads generated artifacts", async () => {
    mockedGenerate.mockResolvedValueOnce(makeResult());
    openGeneratePage();
    fireEvent.click(screen.getByTestId("generate-submit"));
    await waitFor(() => expect(screen.getByTestId("generation-result")).toBeDefined());

    const preview = screen.getByTestId("artifact-preview-deployment.yaml");
    expect(preview.textContent).toContain("kind: Deployment");
    expect(screen.getByRole("button", { name: "Download" })).toBeDefined();
  });

  it("shows a helpful error on the infeasible 422 path", async () => {
    const error = new ApiError(422, "No candidate satisfied your constraints.");
    (error as ApiError & { infeasible?: unknown }).infeasible = {
      generation_id: "gen-x",
      error: "infeasible",
      explanation: "cpu_headroom failed",
    };
    mockedGenerate.mockRejectedValueOnce(error);
    openGeneratePage();
    fireEvent.click(screen.getByTestId("generate-submit"));
    await waitFor(() => {
      expect(screen.getByText(/No candidate satisfied your constraints/i)).toBeDefined();
    });
    expect(screen.queryByTestId("generation-result")).toBeNull();
  });
});
