"""Phase 19: tests for the verify_all_phases.py script itself.

The script is the load-bearing gate for the CI live-smoke job, so its
exit-code semantics are contract: 0 only when every check passed, 1 when
any check failed, 1 with a friendly message when the backend is
unreachable. The checks are executed against a fake HTTP client — no
network, no server, no model artifacts.
"""

import importlib.util
import sys
from pathlib import Path

import pytest

_SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "verify_all_phases.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("verify_all_phases", _SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class _FakeResponse:
    def __init__(self, payload=None, status_code: int = 200):
        self._payload = payload if payload is not None else {}
        self.status_code = status_code
        self.text = str(self._payload)

    def json(self):
        return self._payload


_GEN_OK = {
    "generation_id": "g1",
    "status": "recommended",
    "target_selection": {"target": "kubernetes", "source": "user"},
    "artifacts": [{"filename": "deployment.yaml", "round_trip_valid": True, "content": "x"}],
    "requirements": {"cpu_cores": 2},
    "evaluation": {"status": "recommended"},
}

_OPTIMIZE_OK = {
    "analysis_id": "x",
    "recommendation_set": {"status": "recommended", "items": [{"parameter": "replicas"}]},
    "scores": {"baseline": {"score": 0.5}, "optimized": {"score": 0.7}, "improvement": 0.2},
}

_ANALYZE_OK = {
    "analysis_id": "x",
    "configuration": {"source_type": "kubernetes", "application": "api-backend"},
    "features": {"cpu": 2.0, "replicas": 4, "users_per_replica": 2500.0},
    "prediction": {
        "cpu_utilization": 0.25,
        "memory_utilization": 0.5,
        "model_type": "RandomForestRegressor",
    },
    "estimation": {
        "estimated_cost_usd": 1.0,
        "estimated_energy_kwh": 2.0,
        "estimated_carbon_kg_co2e": 3.0,
        "disclaimer": "prototype estimates",
    },
    "constraints": {"satisfied": True, "checks": [{"name": "headroom", "status": "pass"}]},
    "workload": {
        "average_rps": 500.0,
        "traffic_pattern": "bursty",
        "sustainability_priority": "high",
    },
}


class _FakeClient:
    """Programmable stand-in for httpx.Client with realistic payloads."""

    def __init__(self, script: str = "pass"):
        self.script = script
        self.calls: list[str] = []

    def get(self, url: str, **_):
        self.calls.append(url)
        if "/health" in url:
            if self.script == "unreachable":
                raise ConnectionError("refused")
            return _FakeResponse({"status": "ok"}, 200)
        if "/recommendations" in url:
            return _FakeResponse(_OPTIMIZE_OK, 200)
        if "/optimized-config" in url:
            return _FakeResponse(
                {
                    "analysis_id": "x",
                    "source": "stored_original",
                    "optimized_yaml": "# Generated by EcoOps AI\nkind: Deployment",
                    "original_yaml": "kind: Deployment",
                    "diff": ["- replicas: 8", "+ replicas: 4"],
                    "changes": [{"parameter": "replicas"}],
                    "notes": ["note"],
                    "disclaimer": "deploy manually",
                },
                200,
            )
        if "/score" in url:
            return _FakeResponse(
                {
                    "analysis_id": "x",
                    "score": {
                        "score": 0.5,
                        "grade": "C",
                        "components": [
                            {"name": f"c{i}", "raw_value": "1", "score": 0.5, "weight": 0.2, "explanation": "e"}
                            for i in range(5)
                        ],
                    },
                },
                200,
            )
        if "/constraints" in url:
            return _FakeResponse({"analysis_id": "x", "satisfied": True}, 200)
        if "/configuration" in url:
            return _FakeResponse({"analysis_id": "x"}, 200)
        if "/generation/" in url:
            # Unknown ids are 404s; the known g1 replays.
            if url.rstrip("/").endswith("g1"):
                return _FakeResponse(_GEN_OK, 200)
            return _FakeResponse({"detail": "Generation 'x' was not found"}, 404)
        return _FakeResponse({"analysis_id": "x"}, 200)

    def post(self, url: str, **kwargs):
        self.calls.append(url)
        if self.script == "one_fail" and "/analyze" in url:
            return _FakeResponse({"detail": "boom"}, 500)
        if "/validate" in url:
            return _FakeResponse({"valid": True, "errors": []}, 200)
        if "/analyze" in url:
            files = kwargs.get("files") or {}
            uploaded_name = ""
            for item in files.values():
                if isinstance(item, tuple):
                    uploaded_name = item[0]
                    break
            if uploaded_name.endswith(".tf"):
                source = "terraform"
            elif "compose" in uploaded_name:
                source = "docker_compose"
            else:
                source = "kubernetes"
            payload = {**_ANALYZE_OK, "configuration": {**_ANALYZE_OK["configuration"], "source_type": source}}
            return _FakeResponse(payload, 201)
        if "/generate" in url:
            payload = (kwargs.get("json") or {}).get("workload", {})
            if payload.get("expected_users", 0) >= 100_000:
                return _FakeResponse({"detail": "infeasible: no candidate satisfies the constraints"}, 422)
            if payload.get("target") == "puppet" or (kwargs.get("json") or {}).get("target") == "puppet":
                return _FakeResponse({"detail": "Unknown generation target 'puppet'"}, 400)
            return _FakeResponse(_GEN_OK, 201)
        if "/generation/" in url and url.rstrip("/").endswith("/optimize"):
            return _FakeResponse({**_GEN_OK, "weights_used": {"resource": 0.2}}, 200)
        if "/optimize" in url:
            return _FakeResponse(_OPTIMIZE_OK, 201)
        return _FakeResponse({"ok": True}, 200)

    def close(self) -> None:
        pass


def test_all_checks_pass_returns_zero(capsys) -> None:
    module = _load_module()
    module.results.clear()
    fake = _FakeClient("pass")
    exit_code = module.main(client=fake)
    captured = capsys.readouterr().out
    assert exit_code == 0
    assert "ALL CHECKS PASSED" in captured
    assert module.results and all(ok for _, ok, _ in module.results)


def test_any_failed_check_returns_one(capsys) -> None:
    module = _load_module()
    module.results.clear()
    exit_code = module.main(client=_FakeClient("one_fail"))
    assert exit_code == 1
    out = capsys.readouterr().out
    assert "FAILURES" in out


def test_unreachable_backend_returns_one_with_message(capsys) -> None:
    module = _load_module()
    module.results.clear()
    exit_code = module.main(client=_FakeClient("unreachable"))
    assert exit_code == 1
    out = capsys.readouterr().out
    assert "not reachable" in out


def test_record_appends_and_prints(capsys) -> None:
    module = _load_module()
    module.results.clear()
    module.record("demo check", True, "detail")
    out = capsys.readouterr().out
    assert "PASS  demo check  — detail" in out
    assert module.results == [("demo check", True, "detail")]


def test_summarize_counts_failures(capsys) -> None:
    module = _load_module()
    module.results.clear()
    module.record("ok one", True)
    module.record("bad one", False, "why")
    code = module.summarize()
    out = capsys.readouterr().out
    assert code == 1
    assert "1/2" in out
    assert "FAILED: bad one" in out
