"""Phase 16 IaC templates (design doc section 44.6).

Deterministic, boring, commented renderers: one function per target, each
turning a normalized InfrastructureConfiguration (the winning candidate)
into a complete IaC artifact. Every emitted value is literal — no
variables, no interpolation — because the round-trip guarantee requires
the SAME parser that handles user uploads to re-read exactly these values.

Template shapes follow the repo's infrastructure/ example manifests. All
fallbacks are documented constants, never silent guesses.
"""

from __future__ import annotations

from app.parsers.aws_instance_metadata import smallest_covering_instance_type
from app.schemas.infrastructure_schema import InfrastructureConfiguration

DEFAULT_K8S_IMAGE = "ghcr.io/ecoops/generated-app:latest"

# K8s autoscaling is detected from the deployment's annotations, so the
# generated manifest declares it the same way the parser reads it.
_AUTOSCALING_ANNOTATION = "ecoops.ai/autoscaling"
_AUTOSCALING_ENABLED_VALUES = {"true", "enabled", "yes"}


def _fmt(value: float | int | None) -> str:
    """Compact numeric formatting: 2.0 -> '2', 0.5 -> '0.5'."""
    if value is None:
        return ""
    if float(value) == int(value):
        return str(int(value))
    return f"{value:g}"


def _memory_request(config: InfrastructureConfiguration) -> float:
    value = config.memory_request_gb if config.memory_request_gb is not None else 0.25
    return max(value, 0.25)


def _cpu_request(config: InfrastructureConfiguration) -> float:
    value = config.cpu_request if config.cpu_request is not None else 0.25
    return max(value, 0.25)


def render_kubernetes(config: InfrastructureConfiguration) -> str:
    """Render one Deployment manifest (HPA comes as a second document when enabled)."""
    app = config.application
    cpu = _fmt(_cpu_request(config))
    memory_gi = _fmt(_memory_request(config))
    image = config.container_image or DEFAULT_K8S_IMAGE

    autoscaling_annotation = ""
    if config.autoscaling_enabled:
        autoscaling_annotation = (
            f"  annotations:\n"
            f"    {_AUTOSCALING_ANNOTATION}: \"true\"\n"
        )

    deployment = f"""# Generated by EcoOps AI (workload-to-infrastructure, Mode B).
# Prototype guidance: review before use. EcoOps AI never deploys anything.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {app}
  namespace: {config.namespace}
{autoscaling_annotation}  labels:
    app: {app}
    generated-by: ecoops-ai
spec:
  replicas: {max(config.replicas, 1)}
  selector:
    matchLabels:
      app: {app}
  template:
    metadata:
      labels:
        app: {app}
    spec:
      containers:
        - name: {app}
          image: {image}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "{cpu}"
              memory: {memory_gi}Gi
            limits:
              cpu: "{cpu}"
              memory: {memory_gi}Gi
"""
    if not config.autoscaling_enabled:
        return deployment

    # Minimal placeholder HPA (no target utilization metrics): the parser
    # round-trip covers the Deployment; the HPA documents the intent.
    hpa = f"""---
# Autoscaling intent (prototype placeholder; tune metrics before use).
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {app}
  namespace: {config.namespace}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {app}
  minReplicas: {max(config.replicas, 1)}
  maxReplicas: {max(config.replicas * 4, config.replicas + 1)}
"""
    return deployment + hpa


def render_terraform(config: InfrastructureConfiguration) -> str:
    """Render one aws_instance + provider block from the normalized config."""
    instance_type = config.instance_type or smallest_covering_instance_type(
        _cpu_request(config), _memory_request(config)
    )
    if instance_type is None:
        raise ValueError(
            f"No instance type in the metadata table covers "
            f"{_cpu_request(config):g} vCPU / {_memory_request(config):g} GiB; "
            f"refusing to emit an undersized Terraform configuration"
        )
    region = config.region or "us-east-1"
    provider = config.cloud_provider or "aws"
    if provider != "aws":
        # The Phase 12 parser handles aws_instance only; say so instead of
        # emitting a broken provider block for another cloud.
        raise ValueError(
            f"Terraform generation supports provider 'aws' only (got '{provider}'); "
            "the parser and metadata table are AWS-scoped in this prototype"
        )

    storage_block = ""
    if config.storage_gb:
        storage_block = f"""
  root_block_device {{
    volume_size = {int(config.storage_gb)}
    volume_type = "gp3"
  }}
"""

    return f"""# Generated by EcoOps AI (workload-to-infrastructure, Mode B).
# Prototype guidance: review before use. EcoOps AI never deploys anything.
# The AMI is a placeholder; set a real image for your region before applying.
provider "{provider}" {{
  region = "{region}"
}}

resource "aws_instance" "{config.application}" {{
  ami           = "ami-00000000000000000"
  instance_type = "{instance_type}"
  count         = {max(config.replicas, 1)}
{storage_block}
  tags = {{
    Name        = "{config.application}"
    GeneratedBy = "ecoops-ai"
  }}
}}
"""


def render_docker_compose(config: InfrastructureConfiguration) -> str:
    """Render one Compose service from the normalized config.

    Reservations carry the requests; limits carry the configured limits
    (Phase 16 normalization guarantees limits exist for container targets,
    so limits == requests for VM-shaped inputs).
    """
    request_cpu = _fmt(_cpu_request(config))
    request_memory = _fmt(_memory_request(config))
    limit_cpu = _fmt(config.cpu_limit if config.cpu_limit is not None else _cpu_request(config))
    limit_memory = _fmt(
        config.memory_limit_gb if config.memory_limit_gb is not None else _memory_request(config)
    )
    image = config.container_image or DEFAULT_K8S_IMAGE

    return f"""# Generated by EcoOps AI (workload-to-infrastructure, Mode B).
# Prototype guidance: review before use. EcoOps AI never deploys anything.
services:
  {config.application}:
    image: {image}
    deploy:
      replicas: {max(config.replicas, 1)}
      resources:
        limits:
          cpus: "{limit_cpu}"
          memory: {limit_memory}g
        reservations:
          cpus: "{request_cpu}"
          memory: {request_memory}g
"""


def render_terraform_plus_kubernetes(
    config: InfrastructureConfiguration,
) -> list[tuple[str, str]]:
    """Combo target: Terraform provisions the node VMs, K8s runs the workload."""
    return [
        ("main.tf", render_terraform(config)),
        ("deployment.yaml", render_kubernetes(config)),
    ]
